version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  producer:
    build:
        context: .
        dockerfile: Dockerfile-producer
    ports:
      - "8000:5000"
    volumes:
     - ./producer:/app
    command: >
      sh -c "python producer.py"
    depends_on:
      - kafka

  consumer:
    build:
        context: .
        dockerfile: Dockerfile-consumer
    ports:
      - "8001:5001"
    volumes:
     - ./consumer:/app
    command: >
      sh -c "python consumer.py"
    depends_on:
      - kafka
