FROM python:3.9-alpine3.20
LABEL maintainer="patrykpawluk"

ENV PYTHONUNBUFFERED 1

RUN apk update && apk add bash gcc librdkafka-dev python3-dev musl-dev openjdk11
COPY ./requirements.txt /tmp/requirements.txt
COPY ./consumer /app
WORKDIR /app
EXPOSE 5001

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    /py/bin/pip install -r /tmp/requirements.txt && \
    rm -rf /tmp && \
    adduser \
        --disabled-password \
        --no-create-home \
        flask-user

ENV PATH="/py/bin:$PATH"

USER root
